# .github/workflows/ssl_check.yml

name: Daily Skylark SSL Certificate Check

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  check-certificate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Install swift-nav suite
      run: curl -sL https://raw.githubusercontent.com/swift-nav/suite/main/install.sh | bash

    # --- THIS IS THE CRITICAL FIX ---
    # This step ensures that the swift command is findable by the system.
    - name: Add swift-nav to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Run SSL Check Script
      env:
        SKYLARK_USERNAME: ${{ secrets.SKYLARK_USERNAME }}
        SKYLARK_PASSWORD: ${{ secrets.SKYLARK_PASSWORD }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        PAGERDUTY_ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
      run: python3 ssl_check_skylark.py

