name: Daily Skylark SSL Certificate Check

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  check-certificate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Create Venv and Install Dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: Look Inside File for TCPDriver # <-- THIS STEP ANSWERS YOUR QUESTION
      run: |
        source venv/bin/activate
        # First, find the base path of the sbp library
        SBP_PATH=$(python3 -c "import sbp; print(sbp.__path__[0])")
        # Construct the full path to the target file
        TARGET_FILE="$SBP_PATH/client/drivers/network_drivers.py"
        echo "--- Searching for 'class TCPDriver' inside the file: $TARGET_FILE ---"
        # Use 'cat' to read the file and 'grep' to search for the class
        # The '|| true' ensures the workflow doesn't fail if grep finds nothing
        cat $TARGET_FILE | grep "class TCPDriver" || true

    - name: Verify and Run Script
      run: |
        source venv/bin/activate
        echo "--- Running verification with corrected import path ---"
        # We use the corrected module name here
        python3 -c "from sbp.client.drivers.network_drivers import TCPDriver; print('--- DEEP VERIFICATION SUCCESS ---')"
        python3 ssl_check_skylark.py
