name: Daily Skylark Certificate Check

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  check-certificate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Clone SBP Library
      run: git clone https://github.com/swift-nav/libsbp.git

    - name: Create Venv and Install Dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        # First, install all other dependencies from the requirements file
        python3 -m pip install -r requirements.txt
        # NOW, install the complete SBP library with tools from our local clone
        python3 -m pip install ./libsbp/python[tools]

    - name: Capture Skylark Stream and Convert to JSON
      run: |
        source venv/bin/activate
        # The tools are now correctly installed in the venv, so this will work
        timeout 60s python -m sbp.client.tools.ntrip_client \
          --username ${{ secrets.SKYLARK_USERNAME }} \
          --password ${{ secrets.SKYLARK_PASSWORD }} \
          --url https://eu.l1l2.skylark.swiftnav.com:2101/SSR-integrity \
          --lat 52.149 --lon 13.096 | python -m sbp.client.tools.rtcm3_to_json > log.json

    - name: Check Certificate Expiration from JSON
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        PAGERDUTY_ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
      run: |
        source venv/bin/activate
        python3 check_json.py
