name: Daily Skylark Certificate Check

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  check-certificate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Create Venv and Install Dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: Capture Skylark Stream and Convert to JSON
      run: |
        source venv/bin/activate
        # Run the swift tools for 60 seconds and pipe the output to the json converter
        # We use 'timeout' to ensure the command stops automatically
        timeout 60s swift ntripping \
          --username ${{ secrets.SKYLARK_USERNAME }} \
          --password ${{ secrets.SKYLARK_PASSWORD }} \
          --url https://eu.l1l2.skylark.swiftnav.com:2101/SSR-integrity \
          --lat 52.149 --lon 13.096 | swift rtcm32json > log.json

    - name: Check Certificate Expiration from JSON
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        PAGERDUTY_ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
      run: |
        source venv/bin/activate
        # Run our new, simpler python script to check the file
        python3 check_json.py
