name: Daily Skylark SSL Certificate Check

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  check-certificate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Create Venv and Install Dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: Look Inside File for TCPDriver
      run: |
        source venv/bin/activate
        SBP_PATH=$(python3 -c "import sbp; print(sbp.__path__[0])")
        TARGET_FILE="$SBP_PATH/client/drivers/network_drivers.py"
        echo "--- Searching for 'class TCPDriver' inside the file: $TARGET_FILE ---"
        cat $TARGET_FILE | grep "class TCPDriver" || true

    - name: Verify and Run Script
      # THIS 'env' BLOCK IS THE FIX.
      # It securely passes your GitHub Secrets to the Python script as environment variables.
      env:
        SKYLARK_USERNAME: ${{ secrets.SKYLARK_USERNAME }}
        SKYLARK_PASSWORD: ${{ secrets.SKYLARK_PASSWORD }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        PAGERDUTY_ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
      run: |
        source venv/bin/activate
        echo "--- Running verification with corrected import path ---"
        python3 -c "from sbp.client.drivers.network_drivers import TCPDriver; print('--- DEEP VERIFICATION SUCCESS ---')"
        python3 ssl_check_skylark.py
