name: Daily Skylark SSL Certificate Check

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  check-certificate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Create virtual environment
      run: python3 -m venv venv

    - name: Install dependencies in virtual environment
      run: |
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        python3 -m pip install requests sbp

    - name: Run SSL Check Script
      env:
        SKYLARK_USERNAME: ${{ secrets.SKYLARK_USERNAME }}
        SKYLARK_PASSWORD: ${{ secrets.SKYLARK_PASSWORD }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        PAGERDUTY_ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
      run: venv/bin/python ssl_check_skylark.py

